version: "3"
services:
  postgres:
    image: postgres:15.1
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env

  backend:
    build: blog-summary-backend/.
    env_file:
      - ./blog-summary-backend/.env
    ports:
      - "4001:5000"
    depends_on:
      - postgres
    networks:
      - postgres
  frontend:
    build: blog-summary-frontend/.
    ports:
      - "3000:3000"

networks:
  postgres:
    driver: bridge